### ISSUE TITLE
Can not receive file collection.

### ISSUE THREAD

**Issue by superuser123** [ttacon/box#3]
I'm trying to use this package.
First, I tried to upload a file.  Okay, uploading was successful, but error occured.
"json: Unmarshal(nil *boxFileCollection)

And I have a question. In order to download a file using your package, I have to know the file's id, how can i know?

Thanks in advance.

**Comment by superuser123** [comment]
I found a bug in files.go.
And I committed the correction.

**Comment by ttacon** [comment]
Hey! Sorry for any issues you've had. Could you update me as to what you're issue was? Sometimes this seems like a moving target, and I haven't had the chance to set up tests to monitor for API changes. I saw your [commit](https://github.com/superuser123/box/commit/faa2e7daaf9309dabf56b4af20e7c15729718d3d) on your branch. If you'd like to open a PR contributions are always welcome (otherwise I'm just going to pull the change in).
